project_id = "nrwhfikwgrlibpmurfin"

[functions.analyze-image]
verify_jwt = false

[functions.analyze-batch]
verify_jwt = false

[functions.check-version]
verify_jwt = false

[functions.suggest-caption]
verify_jwt = false

[functions.ocr-correction]
verify_jwt = false

[functions.ai-smart-fix]
verify_jwt = false
